name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instantiate docs/
        shell: julia --color=yes {0}
        run: |
          using Pkg: Pkg
          Pkg.activate("docs")
          Pkg.instantiate()

      - name: Build docs and deploy to the gh-pages branch
        shell: julia --color=yes {0}
        run: |
          using Pkg: Pkg
          dir = pwd()
          Pkg.activate("docs")
          include(joinpath(dir, "docs", "make.jl"))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

